spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password:
